ISFinder2 <- function(){
  if (!require("BiocManager", quietly = TRUE)) install.packages("BiocManager")
  if (!require("Biostrings")) BiocManager::install("Biostrings")
  if (!require("textreadr")) install.packages("textreadr")
  if (!require("seqinr")) install.packages("seqinr")
  library(Biostrings)
  library(textreadr)
  library(seqinr)
  IS <- readline(prompt="Enter IS sequence: ")
  if(nchar(IS) == 0){
    IS <- "GGTTCTGTTGCAAAGTTGAATTTATAGTATAATTTTAACAAAAAGGAGTCTTCTGTATGAACTATTTCAGATATAAACAATTTAACAAGGATGTTATCACTGTAGCCGTTGGCTACTATCTAAGATATGCATTGAGTTATCGTGATATATCTGAAATATTAAGGGGACGTGGTGTAAACGTTCATCATTCAACGGTCTACCGTTGGGTTCAAGAATATGCCCCAATTTTATATCAAATTTGGAAGAAAAAGCATAAAAAAGCTTATTACAAATGGCGTATTGATGAGACGTACATCAAAATAAAAGGAAAATGGAGCTATTTATATCGTGCCATTGATGCAGAGGGACATACATTAGATATTTGGTTGCGTAAGCAACGAGATAATCATTCAGCATATGCGTTTATTAAACGTCTCATTAAACAATTTGGTAAACCTCAAAAGGTAATTACAGATCAGGCACCTTCAACGAAGGTAGCAATGGCTAAAGTAATTAAAGCTTTTAAACTTAAACCTGACTGCCATTGTACATCGAAATATCTGAATAACCTCATTGAGCAAGATCACCGTCATATTAAAGTAAGAAAGACAAGGTATCAAAGTATCAATACAGCAAAGAATACTTTAAAAGGTATTGAATGTATTTACGCTCTATATAAAAAGAACCGCAGGTCTCTTCAGATCTACGGATTTTCGCCATGCCACGAAATTAGCATCATGCTAGCAAGTTAAGCGAACACTGACATGATAAATTAGTGGTTAGCTATATTTTTTACTTTGCAACAGAACC"}
  Gene <- readline(prompt="Enter gene sequence: ")
  if(nchar(Gene) == 0){
    Gene <- "TTGACAAAGAAATATTTAAACACCCAGAATGAAATATCAGCATTTTGGAATACTCAAAAGATATTTAAAAAATCAATTGACAATAGAAAAGGACAGGAAAGTTTTGTTTTTTATGACGGCCCCCCAACTGCAAATGGCCTTCCTCATGCTGGCCATGTTCTTGGAAGAGTAATCAAGGATTTAGTTGCAAGATTAAAAACTATGCAAGGTTTTTATGTAGAAAGAAAAGCAGGATGGGATACCCATGGCTTACCAGTTGAATTAGAGGTTGAAAAAAAAATTGGAATTAAAGGAAAACAAGACATTGAAAAGTATGGAATAGAAAATTTTATAAATGAATGTAAAAAAAGTGTATTTAATTATGAAAAAGAATGGCGGGATTTTTCTAAAGATTTAGGATACTGGGTTGACATGGACTCCCCCTATATAACTCTTGAGAATAATTATATTGAAAGTGTATGGAATATATTATCTACATTCCATAAAAAAGGACTATTATATAAGGGACATAAGGTGACTCCTTATTGTACACATGATCAAACCGCTTTAAGTTCTCATGAAGTAGCGCAAGGCTATAAAAACGTTAAAGATTTATCAGCTGTTGTTAAATTTCAACTTACAAATAGTAAAGATACTTATTTCTTAAGTTGGACTACCACTCCCTGGACTTTGCCTGCAAATGTAGCATTAGCTATAAATAAAGATCTTAATTATTCAAAAATTCGGGTAGAAAATGAGTATTATATCTTAGCTACAGATCTAATTAATTCTATAATAACTGAAAAATACGAAATTATTGATACCTTTTCAGGAAGTAATTTAATTAATTTAAAATACATTCCTCCTTTTGAAAGCGACGGTTTAGTTAATGCATATTACGTTGTTGATGGAGAATTTGTTACTAACTCAGAAGGAACTGGTATTGTTCATATAGCACCAGCTCATGGGGAAGATGACTACCAATTGGTTTTAGAGCGTGATTTGGATTTCTTAAATGTTATAACAAGAGAAGGAGTATATAATGATAGGTTCCCTGAATTAGTTGGTAATAAAGCTAAAAATAGTGATATAGAAATCATAAAATTATTATCCAAAAAACAACTTTTATATAAAAAACAAAAATATGAGCATAATTATCCTCATTGTTGGAGATGTGGTAATCCTTTGATATATTATGCGATGGAAGGTTGGTTTATTAAAACAACTAATTTTAAGAATGAAATTATTAACAATAATAATAATATAGAGTGGTTTCCTTCTCATATTAAGGAAGGGAGAATGGGAAATTTCTTAGAAAATATGGTTGATTGGAACATTGGTAGAAATAGATATTGGGGAACACCATTAAATGTATGGATTTGCAATGATTGTAATCACGAATACGCACCAAGTAGTATTAAGGATTTACAAAATAATTCCATCAATAAAATTGATGAAGATATTGAGTTGCATAGACCTTATGTTGATAATATCACTCTTAGTTGCCCTAAGTGTAATGGGAAAATGTCTCGAGTAGAAGAAGTAATCGATGTTTGGTTTGATAGCGGCTCTATGCCGTTTGCTCAGCATCATTATCCTTTTGATAACCAGAAAATTTTTAATCAACACTTTCCAGCTGATTTTATTGCAGAAGGAGTTGATCAAACGAGAGGCTGGTTTTACAGTTTACTAGTAATTTCTACTATTCTAAAAGGAAAATCTTCTTATAAACGTGCTTTATCTTTAGGACATATTCTAGACAGTAATGATAAAAAAATGTCTAAAAGTAAAGGAAACGTTATTAATCCAACTGAATTAATTAATAAGTACGGAGCCGATTCTTTAAGATGGGCCTTAATTTCGGATAGTGCTCCATGGAATAACAAAAGATTCTCAGAAAATATAGTAGCTCAGACCAAATCGAAATTTATAGATACGCTTGATAATATTTATAAATTTTATAATATGTATAATAAAATAGATCACTATAATCCTAATAATGAAATTACAAAAAGTAGAAATACATTAGATAATTGGGCTCTTTCTCGCTTAAACACCTTAATAAAAGAAAGTAATATTTATGTAAATAATTACGATTTCACTTCCGCAGCCAGATTAATTAACGAATATACCAATACAATAAGTAATTGGTATATTCGGAGATCGAGAGGACGATTTTGGGAACAAGGAATTTCTAACGATAAAAAAGATGCGTACAATACGCTTTATGAAATTTTAACAACTTTATCAAGACTAGTGGCTCCATTTGTTCCATTTATATCTGAAAAAATCCATTATAATTTGACTGGAAAAAGTGTGCATTTACAAGATTATCCACAATATAAAGAAAGTTTTATTAATCAAGCATTGGAAGATGAAATGCATACCGTTATAAAAATTGTAGAATTATCTAGACAGGCTCGCAAAAATGCAGATTTAAAAATTAAGCAACCTTTATCGAAAATGGTGATTAAACCTAATAGTCAATTAAACTTAAGTTTTTTACCTAATTACTATTCAATAATAAAAGACGAATTAAATATAAAAAACATTGAATTAACTGATAATATTAATGACTATATTACCTATGAGCTTAAATTGAATTTTTCTTCTGTGGGACCAAAACTAGGGAACAAAACGAAAAATATTCAAACATTGATAGACTCCCTATCAGAGTATGATAAAAAAAGTTTAATTGAGTCTAATAACTTCAAAAGTTTATCTTCTGATGCTGAGTTAACTAAGGATGATTTTATAATTAAAACCTTACCTAAGGATAGTTATCAACTCAGTGAAGATAATGACTGCGTTATATTATTAGATAAAAATTTATCTCCTGAATTAATTCGCGAAGGACATGCTAGAGAGCTCATTAGATTAATTCAACAATTAAGAAAAAAGAAAAATTTACCAATAAATCAACGTATTGATATTTATATCGGTGTAACTGGGGAATTATTAGAATCAATAAAAACCAATAAAAATATGTTTAAAGAAAATTTGCTGATTAAAAATATACACTTAAATGTTATAGATGAATATGAAAATACTATTCATTTTAATAATAAAGAAATAAAAATTTCCTTATTATATTAA"}
  IS <- toupper(IS)
  Gene <- toupper(Gene)
  d <- dir()
  L<-sapply(d,function(x) grep(".csv",x))
  d<-d[sapply(L, function(x) length(x)==0)]
  #print(d)
  indSec <- 1:length(d)
  indCode <- grep(".R",d)
  indData <- grep(".csv",d)
  indSec <- indSec[indSec!=indCode]
  if(length(indData) != 0){
    indSec <- indSec[indSec!=indData]
  }
  secNames <- d[indSec]
  if(length(secNames) == 1){
    if(length(grep(".txt",secNames)) > 0){
      texto <- scan(secNames, what="character", sep="\n")
      indSecs <- grep(">", texto, value = F)
      secs <- texto[indSecs+1]
      secInd <- texto[indSecs]
      secInd <- substr(secInd, 2, nchar(secInd))} 
    else if(length(grep(".docx",secNames)) > 0){
      texto <- read_docx(secNames)
      indSecs <- grep(">", texto, value = F)
      secs <- texto[indSecs+1]
      secInd <- texto[indSecs]
      secInd <- substr(secInd, 2, nchar(secInd))}
  } else if(length(secNames) > 1){
    secs <- c()
    c <- 0
    for(n in secNames){
      c <- c+1
      if(length(grep(".fasta",secNames[1])) > 0){
        sec <- read.fasta(n,as.string=T)}
      else if(length(grep(".txt",secNames[1])) > 0){
        sec <- scan(n, what="character", sep="\n")
        sec <- sec[2]}
      else if(length(grep(".docx",secNames[1])) > 0){
        sec <- read_docx(n)
        indSecs <- grep(">", sec, value = F)
        sec <- sec[indSecs+1]}
      secs[n] <- toupper(sec)}}
  s <- 0
  Sequences <- data.frame()
  PlasmidSize<-c()
  for(sec in secs){
    s <- s + 1
    PlasmidSize[s]<-nchar(sec)
    ISst <- nchar(sec)
    ISed <- 0
    ISsc <- 2e3
    ISlt <- 0
    n    <- 1
    ISsc<- PlasmidSize[s]/20
    while(ISsc[n] > (PlasmidSize[s]/40)){
      n  <- n + 1
      pa <- pairwiseAlignment(pattern = IS, subject = sec,type = "local")
      ISst <- append(ISst,start(subject(pa)))
      ISed <- append(ISed,end(subject(pa)))
      ISsc <- append(ISsc,score(pa))
      ISlt <- append(ISlt,nchar(pattern(pa)))
      substr(sec, ISst[n], ISed[n]) <- strrep("Q",nchar(pattern(pa)))}
    pa <- pairwiseAlignment(pattern = Gene, subject = sec,type = "local")
    GEst <- start(subject(pa))
    GEed <- end(subject(pa))
    GEsc <- score(pa)
    Ranges <- data.frame(start=ISst[2:(length(ISst)-1)],end=ISed[2:(length(ISst)-1)])
    Ranges$`gen start` <- GEst
    Ranges$`gen end` <- GEed
    Ranges$distance <- 0
    Ranges$distance[Ranges$start > GEed] <- Ranges$start[Ranges$start > GEed] - GEed - 1
    Ranges$distance[Ranges$end < GEst] <- GEst - Ranges$end[Ranges$end < GEst] - 1
    Ranges$distance2 <- 0
    GGSS<-Ranges$`gen start`
    GGEE<-Ranges$`gen end`
    ISSS<-Ranges$start 
    ISEE<-Ranges$end
    as.data.frame(rbind(GGSS,ISSS))
    MinDist<-sapply(as.data.frame(rbind(GGSS,ISSS)), min)
    MaxDist<-sapply(as.data.frame(rbind(GGEE,ISEE)), max)
    Ranges$distance2<-PlasmidSize[s]-MaxDist+MinDist
    for(m in 1:length(Ranges$start)){
      Ranges$prev[m] <- substr(sec,Ranges$start[m]-8,Ranges$start[m]-1)
      Ranges$post[m] <- substr(sec,Ranges$end[m]+1,Ranges$end[m]+8)}
    for(m in 1:length(Ranges$start)){
      if(sum(Ranges$prev[m] == Ranges$post) == 0){
        Ranges$prev[m] = ""}
      if(sum(Ranges$post[m] == Ranges$prev) == 0){
        Ranges$post[m] = ""}}
    if (length(secNames) > 1){
      Ranges$sequence <- secNames[s]
    } else if (length(secNames) == 1) {
      Ranges$sequence <- secInd[s]}
    Sequences <- rbind(Sequences,Ranges)}
  print(Sequences)
  write.csv2(Sequences,"ISdistances.csv", row.names = FALSE)
}

